---
memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50001000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: adc
    range: 64K
    offset: '0x40000000'
  - name: dac
    range: 64K
    offset: '0x40040000'

control_registers:
  - led
  - trig

status_registers:
  - reg1

parameters:
  fclk0: 200000000 # FPGA clock speed in Hz
  adc_clk: 125000000