---
memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: ps_control
    offset: '0x64000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: ps_status
    offset: '0x54000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: adc0
    range: 128K
    offset: '0x80000000'
  - name: adc1
    range: 128K
    offset: '0x80040000'
  - name: dac
    range: 128K
    offset: '0x40080000'

control_registers:
  - mmcm
  - precision_dac_ctl
  - precision_dac_data[2]
  - trig
  - rf_adc_ctl[2]
  - adp5071_sync
  - digital_outputs
  - integrate

status_registers:
  - mmcm_sts
  - adc[n_adc]
  - digital_inputs

ps_control_registers:
  - spi_cfg_data
  - spi_cfg_cmd

ps_status_registers:
  - spi_cfg_sts

parameters:
  fclk0: 200000000 # CPU clock speed in Hz
  fclk1: 200000000 # CPU clock speed in Hz
  adc_clk: 240000000
  adp5071_clk: 2400000
  n_adc: 2