---
instrument: oscillo
parent: instruments/default
board: red-pitaya

# ------------------------------------------------------------
# Memory
# ------------------------------------------------------------

parameters:
  fclk0: 200000000
  fclk1: 200000000
  dac_width: 14
  adc_width: 14
  pwm_width: 12
  n_pwm: 4
  n_dac_bram: 3
  n_dac: 2
  n_adc: 2

memory:
  - name: config
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
    protection: read
  - name: dac[n_dac_bram]
    offset: '0x80000000'
    range: 16K
  - name: adc[n_adc]
    offset: '0x86000000'
    range: 32K
  - name: gpio
    offset: '0x41200000'
    range: 64K
  - name: xadc
    offset: '0x43C00000'
    range: 64K

config_registers:
  - spi_in
  - led
  - pwm[n_pwm]
  - addr
  - avg[n_adc]
  - dac_period[n_dac]
  - avg_period
  - avg_threshold
  - n_avg_min[n_adc]
  - dac_select
  - addr_select
  - clken_mask

status_registers:
  - spi_out
  - n_avg[n_adc]
  - avg_ready[n_adc]
  - avg_on_out[n_adc]
  - counter[2]

# ------------------------------------------------------------
# FPGA
# ------------------------------------------------------------

modules:
  - fpga/modules/address
  - fpga/modules/averager

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/pdm_v1_0
  - fpga/cores/bus_multiplexer_v1_0
  - fpga/cores/at93c46d_spi_v1_0
  - fpga/cores/latched_mux_v1_0

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/oscillo/expansion_connector.xdc

# ------------------------------------------------------------
# Drivers
# ------------------------------------------------------------

server:
  includes:
    - instruments/default/server.yml
    - instruments/default/drivers.yml

  drivers:
    - drivers/gpio.hpp
    - drivers/xadc.hpp
    - instruments/oscillo/drivers/laser/laser.hpp
    - instruments/oscillo/drivers/oscillo.hpp
    - instruments/oscillo/drivers/eeprom/eeprom.hpp

# ------------------------------------------------------------
# Misc
# ------------------------------------------------------------

live_zip: live-oscillo.zip
