---
name: dual-dds
board: boards/red-pitaya

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/axis_variable_v1_0

memory:
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K

control_registers:
  - led
  - phase_incr[4]

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 200000000
  adc_clk: 125000000
  dac_width: 14
  adc_width: 14
  n_adc: 2

xdc:
  - ./xdc/ports.xdc
  - ./xdc/clocks.xdc

drivers:
  - server/drivers/common.hpp
  - ./dual_dds.hpp

web:
  - web/koheron.ts
  - ./web/dual_dds.ts
  - ./web/app.ts
  - ./web/control.ts
  - ./web/index.html
  - web/main.css
  - web/navigation.ts