---
name: decimator
board: boards/red-pitaya
version: 0.1.0

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

control_registers:
  - led
  - dac[n_dac]

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 166666667
  adc_clk: 125000000
  adc_width: 14
  dac_width: 14
  n_adc: 2
  n_dac: 2
  cic_differential_delay: 1
  cic_decimation_rate: 256
  cic_n_stages: 6

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

drivers:
  - server/drivers/common.hpp
  - ./decimator.hpp

web:
  - web/index.html
  - web/main.css
  - web/navigation.ts