---
memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

control_registers:
  - led
  - dac[n_dac]

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 166666667
  adc_clk: 125000000
  adc_width: 14
  dac_width: 14
  n_adc: 2
  n_dac: 2
  cic_differential_delay: 1
  cic_decimation_rate: 256
  cic_n_stages: 6