---
name: cluster
board: boards/red-pitaya

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axis_variable_v1_0
  - fpga/cores/bus_multiplexer_v1_0
  - fpga/cores/pulse_generator_v1_0
  - fpga/cores/edge_detector_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: ctl_clk
    offset: '0x70000000'
    range: 4K

control_registers:
  - led
  - phase_incr[2]
  - ctl_sata
  - pulse_width
  - pulse_period
  - trigger

status_registers:
  - adc[n_adc]
  - sts_sata

parameters:
  fclk0: 200000000
  adc_clk: 125000000
  dac_width: 14
  adc_width: 14
  n_dac: 2
  n_adc: 2

xdc:
  - ./ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - ./sata.xdc
  - ./expansion_connector.xdc

drivers:
  - server/drivers/common.hpp
  - ./cluster.hpp

web:
  - web/index.html