---
name: laser-controller
board: boards/red-pitaya
version: 0.1.0

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/pdm_v1_0
  - fpga/cores/pulse_generator_v1_0
  - fpga/cores/comparator_v1_0
  - fpga/cores/bus_multiplexer_v1_0
  - fpga/cores/saturation_v1_0
  - fpga/cores/at93c46d_spi_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
    protection: read
  - name: xadc
    offset: '0x43C00000'
    range: 64K

control_registers:
  - led
  - laser_current
  - laser_control
  - power_setpoint
  - dac[n_dac]
  - eeprom_ctl

status_registers:
  - adc[n_adc]
  - pid_control
  - eeprom_sts

parameters:
  fclk0: 200000000
  dac_width: 14
  adc_width: 14
  pwm_width: 12
  n_pwm: 4
  n_dac: 2
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - ./expansion_connector.xdc

drivers:
  - server/drivers/common.hpp
  - server/drivers/xadc.hpp
  - server/drivers/laser.hpp
  - server/drivers/eeprom.hpp

web:
  - web/koheron.ts
  - web/imports.ts
  - web/laser.ts
  - web/laser-control.html
  - ./app.ts
  - ./index.html
  - web/main.css
  - web/navigation.ts
  - web/navigation.html