---
name: spectrum
board: boards/red-pitaya

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
    protection: read
  - name: dac[n_dac]
    offset: '0x80000000'
    range: 8K
  - name: spectrum
    offset: '0x86000000'
    range: 16K
  - name: demod
    offset: '0x88000000'
    range: 16K
  - name: noise_floor
    offset: '0x8A000000'
    range: 16K
  - name: peak_fifo
    offset: '0x43C10000'
    range: 64K
  - name: gpio
    offset: '0x41200000'
    range: 64K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: rambuf
    offset: '0x1E000000'
    range: 8M

control_registers:
  - led
  - laser_current
  - laser_control
  - power_setpoint
  - addr
  - substract_mean
  - ctl_fft
  - avg
  - dac_period[n_dac]
  - peak_address_low
  - peak_address_high
  - peak_address_reset
  - avg_period
  - avg_threshold
  - n_avg_min
  - eeprom_ctl

status_registers:
  - spi_out
  - pid_control
  - n_avg
  - peak_address
  - peak_maximum
  - avg_ready
  - avg_on_out
  - eeprom_sts

parameters:
  fclk0: 200000000
  fclk1: 166666667
  sampling_rate: 125000000
  wfm_size: 4096
  dac_width: 14
  adc_width: 14
  pwm_width: 12
  n_pwm: 4
  n_dac: 2

# ------------------------------------------------------------
# FPGA
# ------------------------------------------------------------

modules:
  - fpga/modules/address/config.yml
  - fpga/modules/averager/config.yml
  - fpga/modules/spectrum/config.yml
  - fpga/modules/peak_detector/config.yml

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/pdm_v1_0
  - fpga/cores/bus_multiplexer_v1_0
  - fpga/cores/latched_mux_v1_0
  - fpga/cores/saturation_v1_0
  - fpga/cores/at93c46d_spi_v1_0

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - ./expansion_connector.xdc

# ------------------------------------------------------------
# Drivers
# ------------------------------------------------------------

drivers:
  - server/drivers/common.hpp
  - server/drivers/xadc.hpp
  - server/drivers/laser.hpp
  - server/drivers/modulation.hpp
  - server/drivers/eeprom.hpp
  - ./spectrum.hpp

# ------------------------------------------------------------
# Web
# ------------------------------------------------------------

web:
  - web/koheron.ts
  - web/jquery.flot.d.ts
  - web/laser.ts
  - ./web/spectrum.ts
  - ./web/app.ts
  - web/main.css
  - web/average.ts
  - web/modulation.ts
  - ./web/plot.ts
  - ./web/index.html
  - web/navigation.ts