---
instrument: cluster
parent: default
board: red-pitaya

cores:
  - axi_cfg_register_v1_0
  - axi_sts_register_v1_0
  - redp_adc_v1_0
  - redp_dac_v1_0
  - axis_variable_v1_0
  - bus_multiplexer_v1_0
  - pulse_generator_v1_0
  - edge_detector_v1_0

memory:
  - name: config
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: cfg_clk
    offset: '0x70000000'
    range: 4K

config_registers:
  - led
  - dac[n_dac]
  - phase_incr[2]
  - cfg_sata
  - pulse_width
  - pulse_period
  - trigger

status_registers:
  - adc[n_adc]
  - sts_sata

parameters:
  fclk0: 200000000
  adc_clk: 125000000
  dac_width: 14
  adc_width: 14
  n_dac: 2
  n_adc: 2

xdc:
  - instruments/cluster/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/cluster/sata.xdc
  - instruments/cluster/expansion_connector.xdc

# Drivers

server:
  includes:
    - instruments/default/server.yml
    - instruments/default/drivers.yml

  drivers:
    - instruments/cluster/cluster.hpp
