---
memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: ctl_clk
    offset: '0x70000000'
    range: 4K

control_registers:
  - led
  - phase_incr[2]
  - ctl_sata
  - pulse_width
  - pulse_period
  - trigger

status_registers:
  - adc[n_adc]
  - sts_sata

parameters:
  fclk0: 200000000
  adc_clk: 125000000
  dac_width: 14
  adc_width: 14
  n_dac: 2
  n_adc: 2