# Configuration file for ARM/Ubuntu
#
# (c) Koheron

# Target host
host: armhf

devices:
    # Core devices
    - ../devices/dev_mem.yaml
    - ../middleware/drivers/core/xadc.hpp
    - ../middleware/drivers/core/gpio.hpp
    - ../middleware/drivers/core/oscillo.hpp
    - ../middleware/drivers/core/spectrum.hpp
    - ../middleware/drivers/lase.hpp
    
    # Misc
    - ../middleware/tests/tests.hpp
    - ../middleware/misc/init_tasks.hpp


