---
name: phase-noise-analyzer
board: boards/red-pitaya
version: 0.1.0

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/axis_constant_v1_0
  - fpga/cores/latched_mux_v1_0
  - fpga/cores/tlast_gen_v1_0
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axis_lfsr_v1_0
  - fpga/cores/phase_unwrapper_v1_0
  - fpga/cores/boxcar_filter_v1_0

memory:
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: ram
    offset: '0x1E000000'
    range: 32M
  - name: dma
    offset: '0x80000000'
    range: 64K
  - name: axi_hp0
    offset: '0xF8008000'
    range: 4K

control_registers:
  - led
  - phase_incr[4]
  - cordic

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 125000000
  fclk1: 125000000
  adc_clk: 125000000
  dac_width: 16
  adc_width: 16
  n_adc: 2
  cic_differential_delay: 1
  cic_decimation_rate: 20
  cic_n_stages: 6

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

drivers:
  - server/drivers/common.hpp
  - ./dds.hpp
  - ./dma.hpp

web:
  - web/index.html
  - web/main.css
  - web/koheron.ts