---
name: fft
board: boards/red-pitaya
version: 0.1.0

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/latched_mux_v1_0
  - fpga/cores/axis_constant_v1_0
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/psd_counter_v1_0
  - fpga/cores/comparator_v1_0
  - fpga/cores/saturation_v1_0
  - fpga/cores/pdm_v1_0
  - fpga/cores/at93c46d_spi_v1_0
  - fpga/cores/bus_multiplexer_v1_0

memory:
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: demod
    offset: '0x60000000'
    range: 8K
  - name: psd
    offset: '0x70000000'
    range: 8K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 32K

control_registers:
  - led
  - mmcm
  - ctl_fft
  - psd_valid
  - psd_input_sel
  - phase_incr[2]
  - laser_current
  - laser_control
  - power_setpoint
  - eeprom_ctl

status_registers:
  - adc[n_adc]
  - cycle_index
  - eeprom_sts
  - pid_control

parameters:
  fclk0: 187500000
  adc_clk: 125000000
  dac_width: 14
  adc_width: 14
  pwm_width: 12
  n_adc: 2
  fft_size: 2048
  n_cycles: 1023
  cic_differential_delay: 1
  cic_decimation_rate: 250
  cic_n_stages: 6

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - ./expansion_connector.xdc

drivers:
  - server/drivers/common.hpp
  - server/drivers/xadc.hpp
  - server/drivers/laser.hpp
  - server/drivers/eeprom.hpp
  - ./drivers/fft.hpp
  - ./drivers/demodulator.hpp
  - ./drivers/redpitaya_adc_calibration.hpp

web:
  - web/koheron.ts
  - web/jquery.flot.d.ts
  - web/laser.ts
  - web/navigation.ts
  - web/navigation.html
  - web/imports.ts
  - ./web/app.ts
  - ./web/plot/plot.ts
  - ./web/plot/yunit.html
  - ./web/plot/peak-detection.html
  - ./web/fft/fft.ts
  - ./web/fft/fft-app.ts
  - ./web/fft/fft-window.html
  - ./web/fft/input-channel.html
  - ./web/fft/dds-frequency.html
  - ./web/export-file/export-file.html
  - ./web/export-file/export-file.ts
  - ./web/index.html
  - web/main.css
  - ./web/fft.css
