---
name: fft
board: boards/alpha

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/axis_constant_v1_0
  - fpga/cores/latched_mux_v1_0
  - fpga/cores/edge_detector_v1_0
  - fpga/cores/comparator_v1_0
  - boards/alpha/cores/precision_dac_v1_0
  - boards/alpha/cores/spi_cfg_v1_0
  - fpga/cores/psd_counter_v1_0

memory:
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: demod
    offset: '0x60000000'
    range: 32K
  - name: psd
    offset: '0x70000000'
    range: 32K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

control_registers:
  - mmcm
  - precision_dac_ctl
  - precision_dac_data[2]
  - spi_cfg_data
  - spi_cfg_cmd
  - ctl_fft
  - psd_valid
  - psd_input_sel
  - phase_incr[2]
  - digital_outputs

status_registers:
  - spi_cfg_sts
  - adc[n_adc]
  - cycle_index
  - digital_inputs

parameters:
  fclk0: 200000000
  adc_clk: 250000000
  dac_width: 16
  adc_width: 16
  n_adc: 2
  fft_size: 8192
  n_cycles: 1023
  cic_differential_delay: 1
  cic_decimation_rate: 500
  cic_n_stages: 6

xdc:
  - boards/alpha/config/ports.xdc

drivers:
  - boards/alpha/drivers/common.hpp
  - boards/alpha/drivers/eeprom.hpp
  - boards/alpha/drivers/gpio-expander.hpp
  - boards/alpha/drivers/temperature-sensor.hpp
  - boards/alpha/drivers/power-monitor.hpp
  - boards/alpha/drivers/clock-generator.hpp
  - boards/alpha/drivers/ltc2157.hpp
  - boards/alpha/drivers/ad9747.hpp
  - boards/alpha/drivers/precision-adc.hpp
  - boards/alpha/drivers/precision-dac.hpp
  - boards/alpha/drivers/spi-config.hpp
  - ./fft.hpp
  - ./demodulator.hpp

web:
  - web/koheron.ts
  - web/jquery.flot.d.ts
  - ./web/fft.ts
  - ./web/app.ts
  - ./web/control.ts
  - ./web/plot.ts
  - ./web/temperature-sensor.ts
  - ./web/power-monitor.ts
  - ./web/precision-adc.ts
  - ./web/precision-dac.ts
  - ./web/clock-generator.ts
  - ./web/index.html
  - ./web/main.css

